### ISSUE TITLE
Customer Support

### ISSUE THREAD

**Issue by jinjakim** [Sureplus-Dev/SureplusMobile#25]
### Problem 
03.07 Customer Support에서 다음과 같은 문제를 발견

1. "Send" 버튼 inactive state일때 디자인 수정
[현재 UI]
<img width="346" alt="Screen Shot 2021-03-06 at 7 27 23 PM" src="https://user-images.githubusercontent.com/54109171/110203509-fafb0c80-7eb1-11eb-90d9-69825fac726e.png">
[실제 UI]
<img width="216" alt="Screen Shot 2021-03-06 at 7 27 38 PM" src="https://user-images.githubusercontent.com/54109171/110203519-04847480-7eb2-11eb-8f74-25b0b5edeee9.png">
Text Opacity를 30%로 변경해주면 됩니다.

2. Message가 길어지면 visual을 벗어나고 return key(줄 바꿈)가 작동하지 않습니다.
<img width="364" alt="Screen Shot 2021-03-06 at 7 28 38 PM" src="https://user-images.githubusercontent.com/54109171/110203552-28e05100-7eb2-11eb-9f80-085eced81cd4.png">

3. "Send" 버튼을 눌렀을때 Notification의 contents 수정
[현재 UI]
<img width="377" alt="Screen Shot 2021-03-06 at 7 52 16 PM" src="https://user-images.githubusercontent.com/54109171/110204260-77dbb580-7eb5-11eb-816f-679be4853adb.png">

[실제 UI]
![Customer Support](https://user-images.githubusercontent.com/54109171/110204311-ad809e80-7eb5-11eb-9722-6bd58072e4f0.png)

**Comment by steven991201** [comment]
clear?

**Comment by jinjakim** [comment]
제가 오늘 깃 풀 해서 확인해볼게요!

**Comment by jinjakim** [comment]
오늘 온보딩하면서 확인했습니다! 진짜 수고 많았어용 :)
